# Generated by Django 4.2.30 on 2026-06-05 12:27

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('doc_type', models.CharField(choices=[('doctor_profile', 'Doctor Profile'), ('hospital_policy', 'Hospital Policy'), ('medical_faq', 'Medical FAQ'), ('department_info', 'Department Info')], max_length=30)),
                ('source_id', models.CharField(blank=True, help_text='e.g. doctor pk or policy slug', max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
